name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Limpar cache do npm
        run: npm cache clean --force

      - name: Navegar até o diretório do projeto e instalar dependências
        run: |
          cd aplicativo-loja
          npm install --legacy-peer-deps  # Adicionando a opção para ignorar conflitos

      - name: Rodar os testes
        run: |
          cd aplicativo-loja
          npm test
